hl.on("hyprland.start", function()
    -- nudge the cursor to flush the leftover login-screen cursor buffer (Nvidia quirk)
    hl.exec_cmd("sleep 2.5 && hyprctl dispatch movecursor 9999 9999")
    hl.exec_cmd("sleep 3 && hyprctl dispatch movecursor 1 1")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)