wallpaper {
    monitor = eDP-1
    path = /home/omrxm18/Wallpapers/wallpaperflare.com_wallpaper2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/omrxm18/Wallpapers/FantasticEpicWallpapers.jpeg
    fit_mode = cover
}
